### ISSUE TITLE
line height calculation problems with 1.0.14

### ISSUE THREAD

**Issue by keresztg** [KlausSchaefers/vue-low-code#10]
Hi!

I've upgraded to vue-low-code 1.0.14 and now all the text layers with "Line height: auto" setting in Figma has way off position in vue-low-code. According to the changes in 1.0.14 these elements run into this code in `FigmaService.setLineHeight()`:
```
      /**
       * we might have 'auto', which seems 150%. We set as pixel, because
       * Figma inspect gives the same values.
       */

      if (fStyle.lineHeightUnit === 'INTRINSIC_%' && fStyle.lineHeightPercent) {
        style.lineHeightPX = Math.round(style.fontSize * 1.5);
        return;
      }
```

For a font with size 24 this will result 36px.
If I check the calculated line height in Figma (by clicking on the "Auto" label on the edit style panel) it shows 28.1.
If I dump `fStyle` in `setLineHeight()` I get:
```
line-height:  {
  fontFamily: 'Roboto',
  fontPostScriptName: null,
  fontWeight: 400,
  textAutoResize: 'WIDTH_AND_HEIGHT',
  fontSize: 24,
  textAlignHorizontal: 'LEFT',
  textAlignVertical: 'TOP',
  letterSpacing: 0,
  lineHeightPx: 28.125,
  lineHeightPercent: 100,
  lineHeightUnit: 'INTRINSIC_%'
}
```
So it seems that in this specific case `lineHeightPx` contains the proper value calculated by Figma.

But other developers (see https://github.com/mikaelvesavuori/figmagic/pull/85) thinks that this case should be translated to CSS rule `line-height: normal`. And indeed, that results in a quite decent rendering even though not exactly the same as using `lineHeightPx`.

What do you think about this problem?

Thank,
Gábor

**Comment by keresztg** [comment]
One addition: according to https://www.figma.com/developers/api the `lineHeightPercent` property is deprecated.

**Comment by KlausSchaefers** [comment]
Hi,

I spend some time reverse engineering the lineHeigth issue. For my test cases 'auto' resulted in 150% and the lineHeightPX was wrong...

Can you share you Figma design with me, and I will have another look.

**Comment by KlausSchaefers** [comment]
My current formula is

```
  setLineHeight (style, fStyle) {
    /**
     * If we have pixel line height, everything is easy.
     */
    if (fStyle.lineHeightUnit === 'PIXELS') {
      style.lineHeightPX = fStyle.lineHeightPx
      return
    }

    /**
     * we might have 'auto', which seems 150%. We set as pixel, because
     * Figma inspect gives the same values.
     */
    if (fStyle.lineHeightUnit === 'INTRINSIC_%' && fStyle.lineHeightPercent) {
      style.lineHeightPX = Math.round(style.fontSize * 1.5)
      return
    }

    /**
     * For % we have to take the lineHeightPercentFontSize
     */
    if (fStyle.lineHeightUnit === 'FONT_SIZE_%') {
      style.lineHeight = fStyle.lineHeightPercentFontSize / 100
      return
    }


    /**
     * Defautl is line-heigth in percentage
     */
    style.lineHeight = fStyle.lineHeightPercent / 100
  }
```

**Comment by keresztg** [comment]
Here it is (sorry, it's a little bit quirky):
[letter case test.zip](https://github.com/KlausSchaefers/vue-low-code/files/6497206/letter.case.test.zip)

Should look like this:
![image](https://user-images.githubusercontent.com/43315663/118564486-a48f3180-b770-11eb-9aa2-8056c5d23532.png)

Figma calculates line height as 14.
vue-low-code calculates as 18px which results in:
![image](https://user-images.githubusercontent.com/43315663/118564724-1d8e8900-b771-11eb-922c-2411ac52872c.png)

**Comment by KlausSchaefers** [comment]
Hi, I changed now the 'auto' behavior to 'normal'. The latest version is 1.0.16.

**Comment by keresztg** [comment]
Hi!

I can confirm that version 1.0.16 works perfectly for me.

Closing this issue.

Thanks,
Gábor
