### ISSUE TITLE
Data Binding not working.

### ISSUE THREAD

**Issue by kingzley** [KlausSchaefers/vue-low-code#11]
Hi
Please check, the data binding is not working the Vue application.

I have created a variable in the viewModel field and also paste it on Figma in the Data binding field.

When the input field is changed it does not reflect in this.viewModel.name

**Comment by KlausSchaefers** [comment]
Hi Michael,

there was until yesterday a small regression bug in certain situations. Can you update to 1.0.15 ?

please make also sure that data binding value should be 'name', and the model needs to be passed. 


If this does not solve the issue, can you share your Figma file? Or is it still the one from last week?

Klaus?

**Comment by kingzley** [comment]
Thanks @KlausSchaefers 

I just updated to 1.0.15 and it works now. :)
