### ISSUE TITLE
Custom Component Support

### ISSUE THREAD

**Issue by kingzley** [KlausSchaefers/vue-low-code#12]
Hello again.

I intend on using this InputTag component: https://www.npmjs.com/package/vue-input-tag

I have added the name to the config. 
```
config: {
        components: {
          'InputTag':InputTag
        },
}
```

But I don't know how to get this to work.

Any suggestion?

Thanks.

**Comment by KlausSchaefers** [comment]
Hi,

You also imported the component?

Maybe you need to write a wrapper around, because the low code widgets have
a certain API, on how to read data etc..



Michael Kingsley ***@***.***> schrieb am Di., 18. Mai 2021,
16:47:

**Comment by KlausSchaefers** [comment]
Hi,

take a look here: https://github.com/KlausSchaefers/figma-low-code-custom-component

I wrote a wrapper around the Tag List, to pass the data from the viewMode into the tag list and back. This workaround is a little ugly, I will think about making it better.

Please also node, that you might need to add a frame around the component in Figma, otherwise the position might be wrong.

**Comment by KlausSchaefers** [comment]
The code of the component is

```vue
&lt;template&gt;  &lt;div class=""&gt;      &lt;InputTag v-model="tags" @input="onChange"/&gt;  &lt;/div&gt;&lt;/template&gt;

&lt;script&gt;import InputTag from 'vue-input-tag'export default {  name: "MyComponent",  props: ['value', 'element', 'model', 'config'], // here we get the data passed. The value is the viewModel  data: function () {    return {      tags: ['A']    };  },  components: {    'InputTag': InputTag  },  methods: {    onChange (e) {      // write the changes back      this.value.tags = e    }  },  mounted () {    // read the tags from the viewModel    this.tags = this.value.tags  }};&lt;/script&gt;
```

**Comment by KlausSchaefers** [comment]
The home imports the component as this

```vue
<template>
  <div class="home">
    <Figma :figma="figmaJSON" v-model="viewModel" :config="config"/>
<pre>{{viewModel}}</pre>

  </div>


</template>

<style>
  pre {
    position: fixed;
    right:0px;
    top:0px;
    background: orange;
    width: 200px;
    color:#fff;
  }
</style>

<script>
import Vue from "vue";
import Figma from "vue-low-code";
Vue.use(Figma);

// import JSON file for deployment
import app from './app.json'
import MyComponent from './MyComponent'

export default {
  name: "Home",
  data: function () {
    return {
      figmaJSON: app,
      figmaConfig: {
        figmaFile: "",
        figmaAccessKey: "",
      },
      viewModel: {
        tags: ['Klaus', 'was', 'here']
      },
      config: {
        responsive: [
          { value: "Desktop", label: "Desktop", types: ["desktop"] },
          { value: "Mobile", label: "Mobile", types: ["tablet", "mobile"] },
        ],
        components: {
          'MyComponent': MyComponent
        },
      },
    };
  },
  components: {},
  methods: {
    /**
     * Place your methods here
     */
  },
};
</script>
```

**Comment by KlausSchaefers** [comment]
The result will look like this. The pink box is replaced with your component, which adds the TagList.


![figma-low-code](https://user-images.githubusercontent.com/7108416/118725953-884ecb80-b828-11eb-8200-d934f3424a63.png)

**Comment by kingzley** [comment]
INCREDIBLE!!!!

This worked.
And wrapping it in a frame helped with the positioning issue I encountered.


I can't thank you enough for this. 🙏
I really appreciate @KlausSchaefers . 🙌

**Comment by KlausSchaefers** [comment]
Thanks for the kind works. I also appreciate that you put all the effort in helping me fix those issues. I saw your latest updates, the page look very good! Honestly, I am a bit surprised how good the transformation  :D. If you are done with your project, we could maybe write a short article to advertise the project a little?

I will add in one of the next release some 'auto-wrapping' that should make it easier to include custom components.

**Comment by kingzley** [comment]
Yes. Thank you @KlausSchaefers 
Still making little progress:

Here I hosted the work in progress: https://figma-low-code.herokuapp.com/

This is a video demo of main functionality as at now: https://drive.google.com/file/d/1Dz698AIR1OH49qOLi4X1O6LA8N6Q50bC/view?usp=sharing


Still building, and vue-low-code makes development faster. So would be done soon.

**Comment by KlausSchaefers** [comment]
Very nice!
