### ISSUE TITLE
Error: Importing Components from Figma

### ISSUE THREAD

**Issue by kingzley** [KlausSchaefers/vue-low-code#13]
Hi @KlausSchaefers 

I have a button on figma named ButtonGrey in a frame.

When I call `<ButtonGrey /> `in Vue it doesn't show and throws error in the console:
`[Vue warn]: Unknown custom element: <ButtonGrey> - did you register the component correctly?`

Also, what if I wanted to use a figma frame as a vue component. For example creating a route that points to a figma component, can that be done?

Thanks for the support.

**Comment by KlausSchaefers** [comment]
Hi,

you want to use the design system mode? Like this 

https://www.youtube.com/watch?v=xh95ile-QqY 

https://github.com/KlausSchaefers/figma-design-system-example

**Comment by KlausSchaefers** [comment]
There is now some basic support for the interactive components. Otherwise links will only be followed if the point to screens. Screen are root level dartboards. Components are ignored.

**Comment by kingzley** [comment]
> Hi,
> 
> you want to use the design system mode? Like this
> 
> https://www.youtube.com/watch?v=xh95ile-QqY
> 
> https://github.com/KlausSchaefers/figma-design-system-example

Oh. The design system mode is different from the default figma-low-code environment. 
I didn't realize that.

I solved it by including it in the main.js and it worked.

```
async function init () {
  await Figma.createFigmaDesignlets("fileID", "AccessID")
  
  new Vue({
    router,
    render: h => h(App)
  }).$mount('#app')
}

init()
```

Thank you.

**Comment by kingzley** [comment]
> There is now some basic support for the interactive components. Otherwise links will only be followed if the point to screens. Screen are root level dartboards. Components are ignored.

I don't quite understand what you said here.

For example in route:
```
const routes = [
  {
    path: '/',
    name: 'home',
    component: () => 'FigmaHomeScreen'
  },
]
```

Calling FigmaHomeScreen is not supported because it is at root level? So FigmaHomeScreen is ignored, right? Is that what you mean?

**Comment by KlausSchaefers** [comment]
Yes. The idea of the design system mode is that you can mix normal VUE with Figma based components. Your idea of using explicit routes is interesting. I have to think about that a little.

**Comment by kingzley** [comment]
> Yes. The idea of the design system mode is that you can mix normal VUE with Figma based components. Your idea of using explicit routes is interesting. I have to think about that a little.


Great. Thanks.
