### ISSUE TITLE
Figma Elements extruding out.

### ISSUE THREAD

**Issue by kingzley** [KlausSchaefers/vue-low-code#15]
Hello @KlausSchaefers 

I just noticed a bug which was not previously there. See screenshot below:

<img width="380" alt="del1" src="https://user-images.githubusercontent.com/29164220/120507284-953df400-c3be-11eb-99ab-fdb3d3c4db8f.PNG">
<img width="400" alt="del2" src="https://user-images.githubusercontent.com/29164220/120507295-9707b780-c3be-11eb-8679-24d436f42c46.PNG">
<img width="578" alt="del3" src="https://user-images.githubusercontent.com/29164220/120507299-97a04e00-c3be-11eb-8b2a-568ec2ba67a8.PNG">

Notice the element extrude from the container as indicated by the arrows.

**Comment by KlausSchaefers** [comment]
Hmm, I think I didn't change anything but like me check.

**Comment by KlausSchaefers** [comment]
For me the login looks ok. It is still the sam enigma file?
![Luisa-cloud (2)](https://user-images.githubusercontent.com/7108416/120547735-6ee17e00-c3e9-11eb-968a-ac41b0cbf880.png)
![Luisa-cloud (3)](https://user-images.githubusercontent.com/7108416/120548054-d1d31500-c3e9-11eb-97a9-aeb2687035c1.png)

**Comment by KlausSchaefers** [comment]
There was a small unrelated fix on my system. Anyhow I published as 1.0.18. If the error persists, can you share your project with me? A life link would also do.

**Comment by kingzley** [comment]
The live link is temporarily at: http://figma-low-code.herokuapp.com


I noticed the problem:
When I use the Figma Design system: the issue appears.
```
async function init () {
  await Figma.createFigmaDesignlets("<key>", "<key>")
  
  new Vue({
    router,
    render: h => h(App)
  }).$mount('#app')
}

init()
```


But it worked normal after I commented:
`//await Figma.createFigmaDesignlets("<key>", "<key>")`


So the bug is from using `Figma.createFigmaDesignlets`.

**Comment by KlausSchaefers** [comment]
Ah, it must be related to CSS styles being overwritten. Let me think of a solution.

**Comment by kingzley** [comment]
Hey @KlausSchaefers 
Noticed you closed this. I upgraded to 1.0.19, I saw a slight improvement but the issue is still not fully fixed.

Or is 1.0.19 the latest?
<img width="615" alt="extrude-issue" src="https://user-images.githubusercontent.com/29164220/122452069-c31b5f00-cfa0-11eb-9416-e78785c33c30.PNG">

**Comment by KlausSchaefers** [comment]
I thought the was caused because you also used the Design system mode.
Mixing both is not supported yet. But perhaps feel free to reopen

Michael Kingsley ***@***.***> schrieb am Do., 17. Juni 2021,
20:18:

**Comment by kingzley** [comment]
Oh I see. So that's a different mode. Interesting. 
Would test that for another project. 
Thanks.
