### ISSUE TITLE
Screen doesn't change when button is clicked in mobile responsive view.

### ISSUE THREAD

**Issue by kingzley** [KlausSchaefers/vue-low-code#18]
Hello again @KlausSchaefers 

I have made update to the figma mobile page https://www.figma.com/file/uKgt9PzMeazuh8SqXJQoVs/Figma-low-code-route-test?node-id=0%3A1

When I click the _"Get Started"_ button the url changes to _/register.html_
But the screen doesn't change.

You can test it live on heroku from your phone: http://figma-low-code.herokuapp.com/

Thank you 🙏

**Comment by KlausSchaefers** [comment]
OK, I can reproduce. I will have to take a look. I cannot fix until the weekend, as I am super busy

**Comment by kingzley** [comment]
Ok no problem.
Thanks so much for your efforts so far. I appreciate. 😊

**Comment by KlausSchaefers** [comment]
Thanks for not loosing patience!

**Comment by KlausSchaefers** [comment]
Hi, 

It was easy to fix. Can you try out 1.0.20?

**Comment by kingzley** [comment]
Wow, thanks 🙏.
It works fine.
