### ISSUE TITLE
[Feature request] Toggle hide/show of figma design.

### ISSUE THREAD

**Issue by kingzley** [KlausSchaefers/vue-low-code#19]
Hello @KlausSchaefers 

It'd be nice to have a feature to toggle parts of the figma design. 
That would allow for easy creation of Modals, Nav bars, toast notificationst, popups etc directly from figma and then binded to a viewModel data.

What do you think?

**Comment by KlausSchaefers** [comment]
Hi,

1) there is already an 'Toggle Children' element, that also works with data binding. You could try that.

2) You can try to get enrolled into the interactive components beta. These are already partially supported.

3) You can make an dartboard an 'overlay'. The content will be rendered both the rest.

4) I am aiming to better support Figma animations in the future. 

If none of the solutions help you, what are you thinking about?

Cheers,

Klaus

**Comment by kingzley** [comment]
Seen the Toggle children in smart container. Would test it and get back to you.

For option 2, how can I get enrolled?

**Comment by KlausSchaefers** [comment]
You have to request access at figma. They have somewhere a form


Michael Kingsley ***@***.***> schrieb am So., 20. Juni 2021,
12:17:

**Comment by kingzley** [comment]
Ok I've seen it and requested access.
Thanks.
