### ISSUE TITLE
Camera Data binding not working

### ISSUE THREAD

**Issue by Haiss2** [KlausSchaefers/vue-low-code#27]
![image](https://user-images.githubusercontent.com/34814121/127603588-ef43ca20-b134-4c9a-ba58-e69beaf79706.png)
Hi,
I use the Camera Image Component for dynamic image URL. the Url of the image is:
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4L2nLZR02GNvJb39MGAQvJtsxEy4yRvrp5Q&usqp=CAU and it is binding data to the Camera Image Component. But the image can't show on my screen.
Can you guys help me, please?

**Comment by KlausSchaefers** [comment]
I will check in the next days

Haiss2 ***@***.***> schrieb am Fr., 30. Juli 2021, 07:14:

**Comment by KlausSchaefers** [comment]
Hi,

can you update vue-low-code to 1.0.25? I believe the issue should be fixed.
