### ISSUE TITLE
Data in Grid Components not show correctly

### ISSUE THREAD

**Issue by Haiss2** [KlausSchaefers/vue-low-code#28]
![39592](https://user-images.githubusercontent.com/34814121/127604290-06126615-3157-4bec-be42-5bad518421b8.jpg)
![39594](https://user-images.githubusercontent.com/34814121/127604292-c5934199-5bb3-4b55-b43f-e73a31a538cc.jpg)
![image](https://user-images.githubusercontent.com/34814121/127604327-b6c309ba-b54f-4290-9e19-435adb61d1f1.png)
times: [ {value: 'hello' },{value: 'how' },{value: 'are' }, ,{value: 'you' },]

I show my error in 3 images. can you guys solve this problem?
Why aren't my x-axis labels "hello - how -are -you" respectively?

**Comment by KlausSchaefers** [comment]
Hi, can you bind the grid to time and the label in the grid to value?

Haiss2 ***@***.***> schrieb am Fr., 30. Juli 2021, 07:22:

**Comment by Haiss2** [comment]
I tried, but the labels didn't show anything.
