### ISSUE TITLE
Why is the dependent package used in qux-low-code-example 'qux-lowcode' instead of 'vue-low-code'?

### ISSUE THREAD

**Issue by huangbaihei** [KlausSchaefers/vue-low-code#37]
When I changed to 'vue-low-code', I encountered an error：The qContainer component is not registered

**Comment by KlausSchaefers** [comment]
Hi,

can you update to Luisa-vue? I renamed the package.

```
npm install luisa-vue@2
```

There is also more information here: https://luisa.cloud/help.html
