### ISSUE TITLE
How can I load my project from my local quant-ux database ?

### ISSUE THREAD

**Issue by SharifTanvir** [KlausSchaefers/vue-low-code#5]
I am using local quant-ux back-end. I want to load design from my local database. 

instead of calling API  `https://quant-ux.com/rest/invitation/a2aa10aPSGSjC2X5VPbSeEBkkcxVOSNqR0Gc1iZvv4yidHpmTmdM34LhIzAa/app.json`

I want to call : `http://localhost:8080/rest/invitation/a2aa10aPSGSjC2X5VPbSeEBkkcxVOSNqR0Gc1iZvv4yidHpmTmdM34LhIzAa/app.json`

how can i do this

**Comment by KlausSchaefers** [comment]
Hi, 

you can download the JSON, and pass it as the app instead of the token. So you your Home.vue  do a GET request in the mounted() method and set the result as the app. In the next release I will make the server configurable.
