### ISSUE TITLE
Is there any sample implementation or documentation for custom component?

### ISSUE THREAD

**Issue by im-DJKem** [KlausSchaefers/vue-low-code#64]
I am currently prototyping a SPA application at my workplace using Fimga and vue-low-code.     
I have a feature that I want to control detailed interactions myself, and I was thinking of using a custom component, but I'm not sure how to implement it.     
Do you have any documentation or sample code?       
I checked the following documentation, but could not understand it very well.     

* [KlausSchaefers/vue-low-code: Quant-UX standalone](https://github.com/KlausSchaefers/vue-low-code#custom-components-and-rendering)   
* [Luisa.Cloud - The Low-Code JavaScript Framework](https://luisa.cloud/#/help/custom.html)    

I am mainly interested in the following topics            

* How to pass parameters from a parent component to a child custom component.
* Method binding to custom components.

**Comment by KlausSchaefers** [comment]
Hi,

thanks for reaching out. I just created a small sample project:

https://github.com/KlausSchaefers/luisa-custom-component

The Figma file looks like:

![image](https://github.com/KlausSchaefers/vue-low-code/assets/7108416/9f304f9d-9ad8-4aaa-be1d-b47214e5d3f7)

the main code is here:

https://github.com/KlausSchaefers/luisa-custom-component/blob/main/src/components/ComplexCustomComponent.vue

Does this help?

**Comment by im-DJKem** [comment]
Thank you for your answer.
I think I can solve what I wanted to know by referring to the sample project you provided.       
I will close this Issue.
