### ISSUE TITLE
Connection to quant-ux doesn't work

### ISSUE THREAD

**Issue by aaguirrek** [KlausSchaefers/vue-low-code#67]
When you put the low-code token in quant-ux it indicates a cross origin error with localhost, plus it doesn't download from quant-ux, apparently trying to connect to the quant-ux website and not to the app

**Comment by KlausSchaefers** [comment]
Hi, can you update to luisa-vue@3.0.34?

**Comment by baumheld** [comment]
I had the same problem
Updating from 3.0.28 to 3.0.34 solved the problem

This blocked me for hours, until I found this comment. Maybe you could update [package.json](https://github.com/KlausSchaefers/luisa-vue3-starter/blob/main/package.json)

**Comment by KlausSchaefers** [comment]
Thanks, just did!
