### ISSUE TITLE
Design system mode not compatible with 1.0.8

### ISSUE THREAD

**Issue by ryanmoore-SM** [KlausSchaefers/vue-low-code#7]
### Problem
Trying to use design system mode results in parsing errors and runtime errors in the console

### Details
We downloaded the [figma-design-system-example](https://github.com/KlausSchaefers/figma-design-system-example) and made no modifications and it ran as expected. We then updated to 1.0.8 and the example continued to work. Using the download.js referenced in the README, we attempted to import our own Figma project which resulted in parse errors shown below.

```
figma-design-system-example
vue-low-code version 1.0.8

node download.js <APIKEY> <FILEID>

Download Figma file...
parse image 1 false
parse TopRibbon false
parse Frame 38 false
parse Overview false
...
```
We then reverted back to vue-low-code 0.4.46 and the download.js was successful leading us to believe that the download.js is not compatible with 1.0.8. 

Based on this success we installed vue-low-code version 0.4.46 in our main project, copied over download.js, ran download.js and it didn't report any parsing errors. 

We then used the source code provided in the figma-design-system-example main.js file which resulted in the page loading, however we saw all of these errors in the console indicating the import was not successful.

![image](https://user-images.githubusercontent.com/83981604/117715780-fbf03900-b195-11eb-8232-6cafadd05dce.png)

We then tried the main.js code from the README and encountered the exact same problem.

Is there any guidance you can provide to help us use the design system mode with the latest version of vue-low-code?

### Versions
Node: v14.16.0
npm: 6.14.11
Vue: 2.6.12
Vue-low-code: 1.0.8

**Comment by KlausSchaefers** [comment]
Hi,

thanks for contacting me! I will have a look!

**Comment by KlausSchaefers** [comment]
I see there are some problems with variants... Can you share your Figma file with me Klaus.schaefers@gmail.com?

**Comment by ryanmoore-SM** [comment]
Thanks for the reply! After updating to 1.0.10, I was able to successfully use download.js. I am still seeing errors in the console, but I think we may need to rename things to be valid html element names. We are doing that now.

**Comment by KlausSchaefers** [comment]
Hi,

the lib expects that all components are directly nested in a root frame. Then I would expect that all instances are found. I am not sure why you have multiple instances. Are you using variants?

Klaus

**Comment by KlausSchaefers** [comment]
Was this helping?

**Comment by ryanmoore-SM** [comment]
Sorry for the delay in response. Putting all the components in a root frame fixed my issue.  Thank you so much for your quick response!
