### ISSUE TITLE
[Feature] Import Rich Text Formatting

### ISSUE THREAD

**Issue by kingzley** [KlausSchaefers/vue-low-code#9]
Currently, rich text formats such as **font colors**, **_italics_**, **bold**, etc doesn't import automatically from Figma when using this package.

I am opening this to request for this feature.

Thanks a lot for your efforts in making this gem opensource. @KlausSchaefers :)

**Comment by KlausSchaefers** [comment]
I looked into the topic. Should be done next week.

**Comment by KlausSchaefers** [comment]
Hi,

can you check 1.0.17. This should support basic richt text formats. Some advanced stuff might not work yet, but your example looks good. You might need to download the figma file again.

![Luisa-cloud (1)](https://user-images.githubusercontent.com/7108416/119278017-ac405180-bc1a-11eb-8c2f-8ac8f0812a6e.png)

**Comment by kingzley** [comment]
Awesome. Confirmed. It's working. :)
